[package]
name = "zorvane"
version.workspace = true
edition.workspace = true
description = "Zorvane world and competition simulator"
publish = false

[dependencies]
zorvane-vehicle.workspace = true
terra-transport.workspace = true
terra-autonomy.workspace = true
terra-navigation.workspace = true
terra-experiment.workspace = true
terra-mapping.workspace = true
terra-types.workspace = true
terra-state.workspace = true
terra-control.workspace = true
terra-waypoint.workspace = true
bevy = { version = "0.19.1", features = ["bevy_scene", "bevy_gltf"] }
bevytiles = "0.1.0"
bevy_water = { path = "vendor/bevy_water", default-features = false, features = ["embed_shaders"] }
avian3d = { git = "https://github.com/avianphysics/avian", rev = "af7e99c5c1da386aaa2b4c330e2adc96fa7ca6eb" }
bevy_voxel_world = "=0.17.0"
bevy_procedural_tree = "=0.4.0"
fastrand = "2.3"
zenoh = { version = "1.10.1", default-features = false, features = ["transport_tcp"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
